### ISSUE TITLE
Multiple inheritance for new Type objects

### ISSUE THREAD

**Issue by louisnells** [efficios/barectf#16]
Is it possible to inherit multiple existing user defined data-types in to a new data-type ?

I am assuming all the parent data-types have non-overlapping/unique member fields ...

**Comment by eepp** [comment]
Unfortunately, no, but this is a good idea.

It could work like `$include` where you can specify an array of field types to inherit from:

```yaml
$inherit:
  - parent-type-a
  - parent-type-b
# ...
```

Thanks for the suggestion.
