### ISSUE TITLE
Both Readme.md  and doc\examples  build failed on my PC

### ISSUE THREAD

**Issue by hbsyzbh** [efficios/barectf#4]
Dear sir,
 I used  the  minimal configuration  in https://github.com/efficios/barectf/blob/master/README.md

but show some  Error  which I have no idea with it.
 
$ barectf config.yaml
Error:
  cannot create configuration from YAML file:
  need more than 1 value to unpack

then I try https://github.com/efficios/barectf/tree/master/doc/examples/linux-fs-simple 
the same thing happened.

I try this  on  Ubuntun   and  MingW32  ,  same story.
both use
barectf 2.0.1
Python 3.4.3

It's there any thing that  I  did not notice ?

Thanks!

B.R.
Hwa Treasury Red

**Comment by eepp** [comment]
Problem solved.

Please use barectf v2.0.2 (`pip install --upgrade barectf`).

Thanks for reporting.

**Comment by hbsyzbh** [comment]
Dear sir:

Thanks to your  barectf , we can trace our program and view it via TraceCompass. It works great!

Now we begin to study your program.   We think maybe  " env['domain'] = 'bare' " in config.py  line 71 overwrite the value from yaml.   Now we just delet " env['domain'] = 'bare' " , so our config in yaml can apply.

By the way, do you mind to tell me what tools or IDE are you using  to read & write py  file ?  :) 
Any suggestion to  py beginner ?    :)

Thanks again.

B.R.

**Comment by eepp** [comment]
@hbsyzbh Thanks for your comment.

I could make the user environment variables (in `env`) override the default ones instead of the opposite. From what I understand, you want your own value for `env['domain']`? You could create a new GitHub issue for this.

For developing, I'm using just a regular text editor, no fancy IDE! There are [many Python IDEs](https://wiki.python.org/moin/IntegratedDevelopmentEnvironments) out there but I didn't test any of them, at least not for Python development.

**Comment by hbsyzbh** [comment]
Dear sir @eepp :
    Thanks for your reply。

> From what I understand, you want your own value for env['domain']?

Yes, I am。 And sorry for my bad English。

 > You could create a new GitHub issue for this.

I'd like to.  But sorry for my late,  seems  you have already done this.    :)

>
commit a1a610d43d4762d084feaddcc6378ce2795bcb93
Author: Philippe Proulx <eeppeliteloop@gmail.com>
Date:   Sat Mar 26 03:10:26 2016 -0400
    config: override default env entries
    Signed-off-by: Philippe Proulx <eeppeliteloop@gmail.com>

**Comment by eepp** [comment]
> But sorry for my late, seems you have already done this. :)

Yes, since it was so easy to do. But it's not in a release yet.
