### ISSUE TITLE
What is the license of the generated code?

### ISSUE THREAD

**Issue by neeraj9** [efficios/barectf#8]
The license of the generated c code is unspecified. Can the licensed code be licensed say under BSD (2-clause or 3-clause) or maybe ISC?

**Comment by eepp** [comment]
Good point.

The generated code's license is MIT, like everything else in the project. I will add the headers in the code soon.

**Comment by neeraj9** [comment]
I am not a lawyer but certain sites suggest going for ISC license instead of MIT. Honestly though I dont know the authenticity of the same (see http://forum.freegamedev.net/viewtopic.php?f=7&t=4328 as an example).
